image:
  - Visual Studio 2022
  - Ubuntu
configuration: Release
platform:
  - Win32
  - x64
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
matrix:
  exclude:
    - image: Ubuntu
      TARGET_PLATFORM: Win32
before_build:
- ps: cmake -B Builds -G "Visual Studio 17 2022" -A $env:PLATFORM
- ps: ls .\Builds
- ps: cat .\Builds\SampleAddIn.sln
- sh: sudo apt install uuid-dev
build:
  verbosity: minimal
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - cmake -DCMAKE_BUILD_TYPE=Release; cmake --build .